all: true
dir: '{{.InterfaceDir}}'
filename: mocks.go
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
template: testify
template-schema: '{{.Template}}.schema.json'
packages:
  github.com/j-nowakowski/lzval:
    config:
      all: true